#!/bin/sh

set -e
LINUX_KERNEL="Liquorix" # Liquorix or XanMod 




lb config noauto \
            --distribution bookworm \
            --architecture amd64 \
            --bootappend-live "boot=live components" \
            --apt-recommends false \
            --debian-installer none \
            --cache-indices false \
            --archive-areas "main contrib non-free non-free-firmware" \
            --initramfs live-boot \
            --iso-application "GadroOS" \
            --iso-publisher "GadroOS Projet Powered by luedi" \
            --iso-volume "GadroOS Live" \
            --iso-preparer "GadroOS with live build @LB_VERSION@;" \
            --linux-packages "" \
            --binary-filesystem fat32 \
            --zsync false \
            --mirror-binary https://mirrors.tuna.tsinghua.edu.cn/debian \
            --mirror-binary-security https://mirrors.tuna.tsinghua.edu.cn/debian-security \
            --mirror-bootstrap https://mirrors.tuna.tsinghua.edu.cn/debian \
            --mirror-chroot https://mirrors.tuna.tsinghua.edu.cn/debian \
            --mirror-chroot-security https://mirrors.tuna.tsinghua.edu.cn/debian-security \
            --mirror-debian-installer https://mirrors.tuna.tsinghua.edu.cn/debian \
            "${@}" \
            --debug 