#!/bin/sh

set -e

lb clean


lb config noauto \
            --distribution bookworm \
            --debootstrap-options "--variant=minbase --include=ca-certificates,gnupg,curl" \
            --memtest memtest86+ \
            --architecture amd64 \
            --bootappend-live "boot=live components nottyautologin nosplash" \
            --apt-recommends false \
            --apt-indices false \
            --apt-secure false \
            --chroot-squashfs-compression-type xz \
            --compression xz \
            --debian-installer none \
            --interactive false \
            --firmware-chroot false \
            --cache-indices false \
            --archive-areas "main contrib non-free non-free-firmware" \
            --initramfs live-boot \
            --iso-application "GadroOS" \
            --iso-publisher "GadroOS Projet Powered by luedi" \
            --iso-volume "GadroOS Live" \
            --iso-preparer "GadroOS with live build @LB_VERSION@;" \
            --linux-packages "linux-image-liquorix" \
            --binary-filesystem fat32 \
            --zsync false \
            --updates false \
            --security false \
            --loadlin false \
            --uefi-secure-boot enable \
            --mirror-binary https://mirrors.tuna.tsinghua.edu.cn/debian \
            --mirror-binary-security https://mirrors.tuna.tsinghua.edu.cn/debian-security \
            --mirror-bootstrap https://mirrors.tuna.tsinghua.edu.cn/debian \
            --mirror-chroot https://mirrors.tuna.tsinghua.edu.cn/debian \
            --mirror-chroot-security https://mirrors.tuna.tsinghua.edu.cn/debian-security \
            --mirror-debian-installer https://mirrors.tuna.tsinghua.edu.cn/debian \
            --debug \
            "${@}"