name: Build OS

# 触发条件：当创建tag时
on:
  push:
    tags:
      - 'v*'  # 匹配 v1.0.0, v2.0.1 等格式的tag
      - '*'   # 或匹配所有tag
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Compile
      - name: Build project in Docker container
        run: |
          chmod -R 777 gos-live
          docker run --rm --privileged \
            -v ${{ github.workspace }}/gos-live:/workspace \
            -w /workspace \
            debian:bookworm \
            /bin/bash -c "/workspace/local/scripts/AutoCompile.sh"

      # Upload
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.ref_name }}
          path: |
            gos-live/live-image-amd64.hybrid.iso
            gos-live/live-image-amd64.packages
            gos-live/live-image-amd64.files
            gos-live/live-image-amd64.contents
            gos-live/build.log
          retention-days: 5
